CREATE DATABASE IF NOT EXISTS org_funding_portal
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE org_funding_portal;

CREATE TABLE IF NOT EXISTS hub_lead_applications (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
full_name VARCHAR(150) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
phone_number VARCHAR(30),
role VARCHAR(100) NOT NULL DEFAULT 'Hub Lead',
hub_name VARCHAR(150) NOT NULL,
hub_location VARCHAR(150),
username VARCHAR(100) NOT NULL UNIQUE,
password_hash VARCHAR(255) NOT NULL,
reason_for_application TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;